# Generated by Django 3.0.8 on 2020-08-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('link', models.URLField(max_length=64)),
                ('category', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=64)),
                ('contact_name', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('zipcode', models.CharField(blank=True, max_length=12)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=32)),
                ('keywords', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
